/*
 * Copyright (c) 2025 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* FreeRTOS runtime statistics hooks for RZ/V2H.
 *
 * These functions are called by the FreeRTOS kernel when
 * configGENERATE_RUN_TIME_STATS = 1.  They are placed here (not in the
 * FSP-generated rzv_gen/hal_data.c) so that hal_data.c can be freely
 * regenerated by the FSP configurator without losing customizations.
 *
 * GTM1 is a periodic 1 ms down-counter at 100 MHz (period_counts = 100 000).
 * ulGetRunTimeCounterValue() returns an up-count in ~10 µs units
 * (100 units per ms), wrapping after ~12 h.
 */

#include "hal_data.h"
#include "FreeRTOS.h"

void vPortConfigureTimerForRunTimeStatus(void)
{
#if configGENERATE_RUN_TIME_STATS
    gtm1.p_api->open(gtm1.p_ctrl, gtm1.p_cfg);
    gtm1.p_api->start(gtm1.p_ctrl);
#endif
}

unsigned long ulGetRunTimeCounterValue(void)
{
#if configGENERATE_RUN_TIME_STATS
    static unsigned long ulLastRaw = 0UL, ulOverflows = 0UL;
    unsigned long ulRaw = 0;
    timer_status_t timer_status;

    if (FSP_SUCCESS == gtm1.p_api->statusGet(gtm1.p_ctrl, &timer_status)) {
        /* Invert down-count to up-count: 0 … period_counts */
        ulRaw = gtm1_cfg.period_counts - timer_status.counter;

        if (ulRaw < ulLastRaw) {
            ulOverflows++;
        }

        ulLastRaw = ulRaw;
    }

    /* 1 period = 100 ten-µs units; fraction = ulRaw / 1000 (0..99) */
    return ulOverflows * 100UL + ulRaw / 1000UL;
#else
    return 0;
#endif
}
